### ISSUE TITLE
IRC chat relay throws exceptions

### ISSUE THREAD

**Issue by dopeghoti** [kharidiron/StarryPy3k#25]
Attempting to use `.universe` and `.local` commands in IRC to send messages to the game results in the following excepting being thrown:

```
AttributeError: 'MockPlayer' object has no attribute 'alias'
2016-08-01 16:54:48 - ERROR - starrypy.plugin.command_dispatcher # Unknown exception encountered. Ignoring.
Traceback (most recent call last):
  File "/home/steam/src/StarryPy3k/plugins/command_dispatcher.py", line 131, in run_command
    connection)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 209, in coro
    res = yield from res
  File "/home/steam/src/StarryPy3k/plugins/chat_enhancements.py", line 182, in _local
    sender = self._decorate_line(connection)
  File "/home/steam/src/StarryPy3k/plugins/chat_enhancements.py", line 98, in _decorate_line
    connection.player.alias)
AttributeError: 'MockPlayer' object has no attribute 'alias'
```

**Comment by kharidiron** [comment]
This is due to the way IRC implements the `MockPlayer` object: `MockPlayer`s do not have an actual `factory.connection` instance in the `player_manager`. Because they don't, things like `.local` and `.universe` don't make any sense, and cause the wrapper to throw this error.

I'll need to revisit how `MockPlayer` objects are generated in order to resolve this... which I'm going to put off on, for now. I'll try handling this better in 1.1

**Comment by kharidiron** [comment]
Quick-fix is probably good enough. I still need to work on the MockPlayer connection, but I think that your fix is sufficient for closing this issue.

**Comment by dopeghoti** [comment]
Sounds good to me; I figure once `MockPlayer` is robust enough to handle remotely issued commands (e. g `/kick`) from IRC, this band-aid can be ripped off, or the whitelist of IRC-parsed commands expanded.

**Comment by kharidiron** [comment]
eh.. I'm less inclined to allow /kick from IRC since it will be a pain in the a*\* to handle permission controls. This bot isn't that smart, and I feel like it is better if it stays that way. I'd rather give a well-restricted web GUI for handling these sorts of issues.
